databases:
  - name: booking_system_db
    databaseName: booking_system
    user: booking_system_user

services:
  - type: web
    name: booking-system
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn booking_system.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: booking_system_db
          property: connectionString
