services:
  - type: web
    name: booking-system
    runtime: python
    plan: free
    pythonVersion: "3.11.0"
    buildCommand: "./build.sh"
    startCommand: "gunicorn booking_system.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
    
